<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-MB16O9P" name="com.zzkg.apicases.ZzkgApiCases" tests="7" failures="1" timestamp="07 九月 2017 10:30:30 GMT" time="2.668" errors="0">
  <testcase name="addGoodsToCart" time="0.516" classname="com.zzkg.apicases.ZzkgApiCases"/>
  <testcase name="addGoodsToCart" time="0.564" classname="com.zzkg.apicases.ZzkgApiCases"/>
  <testcase name="addGoodsToCart" time="0.595" classname="com.zzkg.apicases.ZzkgApiCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.zzkg.apicases.ZzkgApiCases.addGoodsToCart(ZzkgApiCases.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- addGoodsToCart -->
  <testcase name="addGoodsToCart" time="0.993" classname="com.zzkg.apicases.ZzkgApiCases"/>
  <testcase name="quickBuy" classname="com.zzkg.apicases.ZzkgApiCases">
    <skipped/>
  </testcase> <!-- quickBuy -->
  <testcase name="exchangeGift" classname="com.zzkg.apicases.ZzkgApiCases">
    <skipped/>
  </testcase> <!-- exchangeGift -->
  <testcase name="checkAddAddress" classname="com.zzkg.apicases.ZzkgApiCases">
    <skipped/>
  </testcase> <!-- checkAddAddress -->
</testsuite> <!-- com.zzkg.apicases.ZzkgApiCases -->
