<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="2216" started-at="2017-08-24T10:20:23Z" finished-at="2017-08-24T10:20:26Z">
    <groups>
    </groups>
    <test name="api" duration-ms="2216" started-at="2017-08-24T10:20:23Z" finished-at="2017-08-24T10:20:26Z">
      <class name="com.zzkg.cases.gift.ExchangeGift">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.zzkg.cases.gift.ExchangeGift@64c64813]" name="beforeClass" is-config="true" duration-ms="64" started-at="2017-08-24T18:20:23Z" finished-at="2017-08-24T18:20:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.zzkg.cases.gift.ExchangeGift@64c64813]" name="beforeMethod" is-config="true" duration-ms="1148" started-at="2017-08-24T18:20:24Z" finished-at="2017-08-24T18:20:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="negativeNumber()[pri:0, instance:com.zzkg.cases.gift.ExchangeGift@64c64813]" name="negativeNumber" duration-ms="69" started-at="2017-08-24T18:20:25Z" finished-at="2017-08-24T18:20:25Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at common.ReadExcel.getExchangeGiftApi(ReadExcel.java:142)
	at datapro.GetApi.exchangeGiftApi(GetApi.java:10)
	at com.zzkg.cases.gift.ExchangeGift.negativeNumber(ExchangeGift.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeNumber -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.zzkg.cases.gift.ExchangeGift@64c64813]" name="afterMethod" is-config="true" duration-ms="1" started-at="2017-08-24T18:20:25Z" finished-at="2017-08-24T18:20:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.zzkg.cases.gift.ExchangeGift@64c64813]" name="beforeMethod" is-config="true" duration-ms="465" started-at="2017-08-24T18:20:25Z" finished-at="2017-08-24T18:20:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="zeroNumber()[pri:0, instance:com.zzkg.cases.gift.ExchangeGift@64c64813]" name="zeroNumber" duration-ms="459" started-at="2017-08-24T18:20:25Z" finished-at="2017-08-24T18:20:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.zzkg.cases.gift.ExchangeGift.zeroNumber(ExchangeGift.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- zeroNumber -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.zzkg.cases.gift.ExchangeGift@64c64813]" name="afterMethod" is-config="true" duration-ms="1" started-at="2017-08-24T18:20:26Z" finished-at="2017-08-24T18:20:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.zzkg.cases.gift.ExchangeGift@64c64813]" name="afterClass" is-config="true" duration-ms="0" started-at="2017-08-24T18:20:26Z" finished-at="2017-08-24T18:20:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.zzkg.cases.gift.ExchangeGift -->
    </test> <!-- api -->
  </suite> <!-- Suite -->
</testng-results>
